#!/bin/sh
#
# This script will be executed *after* all the other init scripts.
# You can put your own initialization stuff in here if you don't
# want to do the full Sys V style init stuff.

touch /var/lock/subsys/local
modprobe -i ip_conntrack_ftp
/sbin/arp -s 211.234.100.1 12:34:AB:CD:43:70

perl /home/root/mtr/check.pl
